#!/usr/bin/env sh

case "$1" in

	debug)
		gcc -c -fmudflap -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror linkedlists.c -lm -o linkedlists.o
		gcc -c -fmudflap -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm tests.c -o tests.o
		gcc -lmudflap tests.o -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm -I/usr/include -o tests
		;;
	
	tests)
		gcc -c linkedlists.c -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm -o linkedlists.o
		gcc -c tests.c -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm -o tests.o
		gcc tests.o -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm -o tests
		;;

	benchmarks)
		gcc -c linkedlists.c -O2 -DNDEBUG -lm -o linkedlists.o
		gcc -c tests.c -O2 -DNDEBUG -lm -o tests.o
		gcc tests.o -lm -o tests
		;;

	cuda)
		gcc -c -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror linkedlists.c -lm -o linkedlists.o
		nvcc -c macro_kernel.cu -o macro_kernel.o
		gcc -c tests.c -Wall -W -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Werror -lm tests.o
		nvcc tests.o -lm -o tests
		;;
	
	*)
		gcc -c linkedlists.c -lm -o linkedlists.o
		;;

esac

exit 0
