#!/usr/bin/env sh

case "$1" in

	debug)
		gcc -c -fmudflap linkedlists.c -o linkedlists.o
		#gcc -fmudflap -lmudflap linkedlists.o -o linkedlists
		;;
	
	tests)
		gcc -c tests.c -o tests.o
		gcc tests.o -o tests
		;;

	*)
		gcc -c linkedlists.c -o linkedlists.o
		#gcc linkedlists.o -o linkedlists
		;;

esac

exit 0
